someengineering/resoto.com

docs/getting-started/installing-with-docker.md
added config for volumes in docker-compose and update docker command (fixed typo)
=> minor getting started fixes

blog/2022-02-04-resoto-query-language-101/index.md
Suggested by a reader to show Resoto is not only tailored to AWS, but supports other cloud provider.
- Fixes #XXXX
=> feat: add references to blog post

news/2022-02-09-v2.0.0a16.md
Adds automatically generated release notes for [v2.0.0a16](https://github.com/someengineering/resoto/releases/tag/2.0.0a16).
=> feat: v2.0.0a16 release notes

docs/getting-started/installing-with-docker.md, docusaurus.config.js
Better explain the use of AWS credentials
=> fix: add note regarding AWS credentials

docs/reference/cli/list.md
Added the documentation for the list and markdown outputs.
- Fixes https://github.com/someengineering/resoto/issues/653
=> Update the list page to include csv and markdown outputs

docs/getting-started/installing-with-docker.md, news/2022-02-09-v2.0.0a16.md, news/2022-02-24-v2.0.0a17.md
Adds automatically generated release notes for [v2.0.0a17](https://github.com/someengineering/resoto/releases/tag/2.0.0a17).
=> feat: v2.0.0a17 release notes

docs/reference/cli/search.md
Update docs for renamed `search` arg
=> fix(docs): update search command documentation to use `--with-edges`

news/2022-03-22-v2.0.0a18.md, openapi/resotocore.yml
Adds automatically generated release notes for [v2.0.0a18](https://github.com/someengineering/resoto/releases/tag/2.0.0a18).
=> feat: v2.0.0a18 release notes

src/pages/about.md
I updated the about us section to use "Resoto".
=> fix: update references to Resoto

docs/getting-started/installing-with-docker.md
Add docs updates for 2.0.0rc0 to this PR
=> Update docs for 2.0.0rc0

news/2022-04-05-v2.0.0rc0.md, openapi/resotocore.yml
Adds automatically generated release notes for [v2.0.0rc0](https://github.com/someengineering/resoto/releases/tag/2.0.0rc0).
=> feat(news): v2.0.0rc0 release notes

docs/getting-started/installing-with-docker.md
Update docs to reflect latest compose file changes.
=> Move core overrides to command args and add cert names

docs/getting-started/installing-with-docker.md, news/2022-04-06-v2.0.0rc1.md
Adds automatically generated release notes for [v2.0.0rc1](https://github.com/someengineering/resoto/releases/tag/2.0.0rc1).
=> feat(news): v2.0.0rc1 release notes

news/2022-04-12-v2.0.0.md
Release notes for 2.0.0
- Fixes #XXXX
=> fix(news): edit release notes for 2.0.0

docs/concepts/security.md, docs/concepts/tagging.md, docs/concepts/tags.md, static/_redirects
Basic tagging concept explained
- Fixes #107 
=> feat(docs): explain the concept of tagging

docs/concepts/search/filters.md, news/2022-04-14-v2.0.1.md
Adds automatically generated release notes for [v2.0.1](https://github.com/someengineering/resoto/releases/tag/2.0.1).
=> feat(news): v2.0.1 release notes

docs/concepts/search/with-clause.md, docs/reference/cli/index.md, docs/reference/cli/templates/add.md, docs/reference/cli/templates/index.md, docs/reference/cli/templates/test.md, docs/reference/templates.md
Describe templates and template commands
=> feat(docs): Describe templates and template commands

docs/contributing/components.md
=> docs(docs): add M1 Mac info

docs/getting-started/installing-with-kubernetes.md
=> fix(docs): Fix helm chart documentation

blog/2022/02-04-resoto-search-101/index.md, blog/2022/03-03-aggregating-search-data/index.md
add zero width space to console output so it's being removed from clipboard copied data
=> docs(docs): add zero width space to blog posts' console output

news/2022-04-22-v2.0.2.md
Adds automatically generated release notes for [v2.0.2](https://github.com/someengineering/resoto/releases/tag/2.0.2).
=> feat(news): v2.0.2 release notes

docs/getting-started/configuring-resoto.md
=> feat(docs): add logging config info

docs/getting-started/installing-with-docker.md
Fix broken anchor link and run command so users don't end up with hundreds of resotoshell containers.
=> fix(docs): fix link and run command

docs/contributing/components.md
=> fix(docs): bump requirements

docusaurus.config.js, src/components/HomepageFeatures/index.tsx, src/pages/index.tsx
=> fix(docs): wording and typos

blog/2022/04-19-digitalocean-support/index.md
=> Rename do -> digitalocean

docs/getting-started/configuring-resoto.md
=> docs: add list config override info

src/pages/index.tsx
Words have been put into my mouth. This is what I actually said. 😂
=> fix(docs): fix quote

news/2022-06-01-community-hour-event.md, package.json, yarn.lock
=> fix(news): community hour event announcement correction

docs/concepts/search/sort-and-limit.md
=> fix(docs): Use a different number for offset and limit

blog/2022/06-09-building-actionable-cloud-infrastructure-metrics/index.md
=> fix(docs): fix sentence

docs/concepts/security.md, docs/getting-started/configuration/core.md, docs/getting-started/configuration/index.md
=> add missing config back

docs/concepts/search/filters.md
=> feat(docs): Improve documentation on filtering values.

package.json, src/pages/index.module.css, src/pages/index.tsx, yarn.lock
Link logos on homepage to internal pages describing how to configure cloud providers rather than external sites.
=> fix(homepage): link logos to internal pages

docs/getting-started/installation/pip.md
Set LC_ALL during password generation to avoid `tr: Illegal byte sequence` on macOS.
=> fix(docs) set LC_ALL

docs/concepts/search/merging-nodes.md
=> fix(docs): correct typo in search

docusaurus.config.js, package.json, src/theme/DocBreadcrumbs.tsx, src/theme/NavbarItem/NavbarNavLink.tsx, yarn.lock
Bumps Docusaurus to 2.0.0-beta.22.
=> build(deps): bump Docusaurus to 2.0.0-beta.22

package.json, yarn.lock
Bumps Docusaurus to [2.0.0-rc.1](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-rc.1).
=> build(deps): bump Docusaurus to 2.0.0-rc.1

.github/CODEOWNERS
=> feat(owner): Add scapecast as docs owner

docs/concepts/resource-management/_category_.json, docs/concepts/resource-management/cleanup.md, docs/concepts/resource-management/index.md, docs/concepts/resource-management/protection.md, docs/concepts/resource-management/tagging.md, docusaurus.config.js, package.json, yarn.lock
Also fixes Concepts > Resource Management docs section, which didn't have sidebar labels set properly.
=> build(deps): bump redocusaurus to 1.3.0

docs/getting-started/configure-cloud-provider-access/aws.md, docs/getting-started/install-resoto/docker.md, docusaurus.config.js, package.json, yarn.lock
Embeds YouTube videos recorded by @meln1k to the relevant Getting Started tutorials.
Also makes some small/minor edits.
=> feat(docs): add videos to docker install & aws config tutorials

docs/getting-started/configure-cloud-provider-access/aws.md, package.json, yarn.lock
=> feat(docs): add AWS profile auth info

docs/getting-started/install-resoto/kubernetes.md
Signed-off-by: kushthedude <kushthedude@gmail.com>
=> feat: update instruction with latest installation for helm

docs/concepts/search/examples.md, docs/getting-started/install-resoto/docker.md, docs/getting-started/install-resoto/kubernetes.md, docs/getting-started/install-resoto/pip.md, docs/how-to-guides/search/find-a-resource.md, docs/how-to-guides/search/find-expired-resources.md, docs/reference/cli/index.md
- not clear when docker setup is ready to go
- find expired certificates search is wrong
- show difference and prefer @utc@ over local @now@
- make clear search is case sensitive
=> fix(docs): Incorporate feedback from Anton

docs/reference/cli/index.md
add keyboard shortcut info
- Fixes #XXXX
=> docs(docs): add shortcut info

docs/getting-started/install-resoto/index.md
=> docs(docs): add server notice

docs/getting-started/install-resoto/docker.md
=> docs(docs): run resh in shell server

docs/getting-started/install-resoto/docker.md
=> docs(docs): remove resh wait, since resh now waits by itself

src/theme/DocSidebarItems/index.tsx
Fixes bold button in dark mode.
=> fix(docs): apply button--outline to release notes button

src/theme/CodeBlock/Content/String.tsx, src/theme/CodeBlock/Content/styles.module.css, yarn.lock
Save and restore user's codewrap setting from local storage.
=> feat: remember code wrap preference

docs/contributing/components.md, docs/getting-started/configure-cloud-provider-access/aws.md, docs/getting-started/configure-cloud-provider-access/digitalocean.md, docs/getting-started/configure-cloud-provider-access/gcp.md, docs/getting-started/configure-cloud-provider-access/kubernetes.md, docs/getting-started/install-resoto/docker.md, docs/getting-started/install-resoto/kubernetes.md, versioned_docs/version-2.X/contributing/components.md, versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/aws.md, versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/digitalocean.md, versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/gcp.md, versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/kubernetes.md, versioned_docs/version-2.X/getting-started/install-resoto/docker.md, versioned_docs/version-2.X/getting-started/install-resoto/kubernetes.md
Define arangodb version and add wait step.
Move optional part to the end.
=> feat(docs): improve k8s installation guide

versioned_docs/version-2.X/getting-started/install-resoto/docker.md
=> fix: use correct docker command for 2.4.x

docs/getting-started/install-resoto/kubernetes.md, versioned_docs/version-2.X/getting-started/install-resoto/kubernetes.md
CNAME of Helm charts repo updated in someengineering/helm-charts#25
=> fix(docs): helm chart repo

docs/reference/data-models/aws.md, docs/reference/data-models/digitalocean.md, docs/reference/data-models/gcp.md, docs/reference/data-models/kubernetes.md, docs/reference/data-models/vsphere.md, versioned_docs/version-2.X/reference/data-models/aws.md, versioned_docs/version-2.X/reference/data-models/digitalocean.md, versioned_docs/version-2.X/reference/data-models/gcp.md, versioned_docs/version-2.X/reference/data-models/kubernetes.md, versioned_docs/version-2.X/reference/data-models/vsphere.md
=> fix(docs): remove extra heading from data models pages

docs/reference/cli/action-commands/http.md, package.json, yarn.lock
Updates documentation for the `http` command to reflect new `--auth` option added in someengineering/resoto#1201
=> fix(docs): update http command documentation

docs/getting-started/install-resoto/kubernetes.md
=> fix(docs): update helm instructions

src/pages/about.md
=> fix(docs): fix typo and component name

docs/reference/cli/action-commands/aws.md, docs/reference/cli/action-commands/index.md, docs/reference/cli/index.md
=> feat(docs): Describe aws command.

docs/getting-started/install-resoto/docker.md, versioned_docs/version-2.X/getting-started/install-resoto/docker.md
=> fix(docker): fix docker exec

blog/2022/10-25-building-an-infrastructure-app-with-resoto-and-streamlit/index.md
Just a nit: right now it's easy to miss where we teach the Python basics. This just adds a header and clarifies some things.
=> docs(docs): refine structure, so people don't accidentally skip the basics

docusaurus.config.js, package.json, yarn.lock
Bumps Docusaurus and other deps.
=> build(deps): bump Docusaurus to 2.2.0

blog/2022/10-25-building-an-infrastructure-app-with-resoto-and-streamlit/index.md
Slight tweaks to changes in #415.
=> fix(blog): tweaks to edits

docs/getting-started/install-resoto/aws/cdk.md, docs/getting-started/install-resoto/aws/cloudformation.md, docusaurus.config.js, src/pages/index.tsx, src/theme/BlogArchivePage/index.tsx, src/theme/BlogListPage/index.tsx, src/theme/BlogPostPage/Metadata/index.tsx, src/theme/DocItem/Metadata/index.tsx, src/theme/MDXPage/index.tsx, src/theme/MDXPage/styles.module.css, src/theme/NavbarItem/NavbarNavLink.tsx, src/utils/socialImageHelper.ts, versioned_docs/version-2.X/getting-started/install-resoto/aws/cdk.md, versioned_docs/version-2.X/getting-started/install-resoto/aws/cloudformation.md
- Adds autogenerated social card images (images defined in frontmatter take precedence)
- Updates tagline (@scapecast please sign off on this)
=> feat: autogenerated social card images

docs/reference/configuration/worker.md, versioned_docs/version-2.X/reference/configuration/worker.md
Add info about peak network connections.
=> fix(docs): add network connection info

docs/reference/data-models/aws/index.md, docs/reference/data-models/digitalocean/index.md, docs/reference/data-models/dockerhub/index.md, docs/reference/data-models/gcp/index.md, docs/reference/data-models/github/index.md, docs/reference/data-models/kubernetes/index.md, docs/reference/data-models/onelogin/index.md, docs/reference/data-models/onprem/index.md, docs/reference/data-models/posthog/index.md, docs/reference/data-models/scarf/index.md, docs/reference/data-models/slack/index.md, docs/reference/data-models/vsphere/index.md, package.json, src/components/ZoomPanPinch.tsx, tools/export_model_images.py, versioned_docs/version-2.X/reference/data-models/aws/index.md, versioned_docs/version-2.X/reference/data-models/digitalocean/index.md, versioned_docs/version-2.X/reference/data-models/gcp/index.md, versioned_docs/version-2.X/reference/data-models/github/index.md, versioned_docs/version-2.X/reference/data-models/kubernetes/index.md, versioned_docs/version-2.X/reference/data-models/onelogin/index.md, versioned_docs/version-2.X/reference/data-models/onprem/index.md, versioned_docs/version-2.X/reference/data-models/slack/index.md, versioned_docs/version-2.X/reference/data-models/vsphere/index.md, yarn.lock
Adds zoom/pan/pinch functionality to data model diagrams.
=> feat(docs): zoom/pan/pinch on data model diagrams

docs/reference/data-models/aws/index.md, docs/reference/data-models/digitalocean/index.md, docs/reference/data-models/dockerhub/index.md, docs/reference/data-models/gcp/index.md, docs/reference/data-models/github/index.md, docs/reference/data-models/kubernetes/index.md, docs/reference/data-models/onelogin/index.md, docs/reference/data-models/onprem/index.md, docs/reference/data-models/posthog/index.md, docs/reference/data-models/scarf/index.md, docs/reference/data-models/slack/index.md, docs/reference/data-models/vsphere/index.md, package.json, src/components/ZoomPanPinch.tsx, tools/export_model_images.py, versioned_docs/version-2.X/reference/data-models/aws/index.md, versioned_docs/version-2.X/reference/data-models/digitalocean/index.md, versioned_docs/version-2.X/reference/data-models/gcp/index.md, versioned_docs/version-2.X/reference/data-models/github/index.md, versioned_docs/version-2.X/reference/data-models/kubernetes/index.md, versioned_docs/version-2.X/reference/data-models/onelogin/index.md, versioned_docs/version-2.X/reference/data-models/onprem/index.md, versioned_docs/version-2.X/reference/data-models/slack/index.md, versioned_docs/version-2.X/reference/data-models/vsphere/index.md, yarn.lock
Open a modal for zooming/panning of diagrams.
=> fix: open zoom in modal

package.json, src/components/ZoomPanPinch.tsx, yarn.lock
Increase max zoom for better viewing experience at small screen widths.
=> fix: increase zoom max scale

docs/concepts/components/plugins/index.md, docs/concepts/resource-management/protection.md, docs/how-to-guides/index.md, docs/reference/api/index.md, package.json, src/components/SectionedDocCardList.tsx, src/css/custom.css, versioned_docs/version-2.X/concepts/components/plugins/index.md, versioned_docs/version-2.X/concepts/resource-management/protection.md, versioned_docs/version-2.X/how-to-guides/index.md, versioned_docs/version-2.X/reference/api/index.md, yarn.lock
Adds new custom `SectionedDocCardList` component for listing docs within categories. Reduces the need for manual management/listing of links to pages nested in subcategories.
=> feat(docs): custom SectionedDocCardList component

static/_redirects
Resolves 404 errors reported by Google Search Console.
=> chore(netlify): add missing redirects

.vscode/extensions.json, .vscode/settings.json, package.json, tools/export_model_images.py
Perform two passes of Prettier formatting when generating API docs.
=> chore: workaround for Prettier bug

tools/export_model_images.py, yarn.lock
=> ci: correct errors/bugs in data model generation script

README.md
As required for the BrowserStack open source program.
=> docs: add Browserstack note to README

docs/getting-started/install-resoto/kubernetes.md, versioned_docs/version-2.X/getting-started/install-resoto/kubernetes.md
=> feat(docs): Update for latest helm chart changes

docs/getting-started/install-resoto/docker.md
update compose version dependency
=> feat(docs): update compose version dependency

docs/getting-started/install-resoto/aws/cloudformation/index.md, docs/getting-started/install-resoto/aws/index.md, src/css/custom.css, versioned_docs/version-2.X/getting-started/install-resoto/aws/cloudformation/index.md, versioned_docs/version-2.X/getting-started/install-resoto/aws/index.md, versioned_docs/version-3.X/getting-started/install-resoto/aws/cloudformation/index.md, versioned_docs/version-3.X/getting-started/install-resoto/aws/index.md
The template is broken and only works in our account. Let's remove it to not confuse our users.
=> fix(docs): add warning to CloudFormation install docs

blog/2022/12-20-integrating-cloud-data-into-existing-sql-workflows-with-cloud2sql/index.md, docusaurus.config.js, src/components/InstallButton.tsx, src/pages/cloud2sql.tsx, src/pages/index.tsx, yarn.lock
=> fix: cloud2sql -> Cloud2SQL

blog/2022/12-21-installing-cloud2sql/index.md
turn off loop and autoplay for videos embedded further down the page
- Fixes #XXXX
=> docs: do not loop do not autoplay!

docs/getting-started/install-resoto/pip.md, versioned_docs/version-3.X/getting-started/install-resoto/pip.md
=> fix(docs): remove synthetic plugins release

docs/getting-started/configure-cloud-provider-access/aws.md, versioned_docs/version-3.X/getting-started/configure-cloud-provider-access/aws.md, yarn.lock
Add link to AWS howto that creates the ResotoAccess role with the required permissions. Ideally we would list the permissions necessary for the current version of Resoto.
=> feat(docs): add link to required AWS role and permissions

blog/2022/10-27-resoto-aws-cdk-construct/index.md, docs/getting-started/install-resoto/aws.md, versioned_docs/version-2.X/getting-started/install-resoto/aws.md, versioned_docs/version-3.X/getting-started/install-resoto/aws.md
=> fix(docs): use t3.large as default instead of t3.medium

.editorconfig, tools/export_model_images.py
=> ci: improve exporter script

docusaurus.config.js
`Resoto Docs` -> `Documentation`
=> fix: footer heading

.github/CODEOWNERS, docusaurus.config.js
Correct typo.
Also update CODEOWNERS file.
=> fix(pwa): apple icon

src/pages/index.module.css
Corrects styling on mobile devices.
=> fix(css): homepage button margins

package.json, tsconfig.json, yarn.lock
Also includes `tsconfig.json` fix.
=> build(deps): bump dependencies

docusaurus.config.js
Adds Some Engineering blog link to navbar.
=> fix: add blog link to navbar

src/pages/index.module.css, src/pages/index.tsx, static/_redirects
=> fix: homepage heading

src/css/custom.css
=> style: sane font weight

docs/getting-started/install-resoto/kubernetes.md, versioned_docs/version-3.X/getting-started/install-resoto/kubernetes.md
=> feat: k8s install remove operator requirement

docs/reference/cli/action-commands/workflows/history.md, docs/reference/cli/action-commands/workflows/index.md, versioned_docs/version-3.X/reference/cli/action-commands/workflows/history.md, versioned_docs/version-3.X/reference/cli/action-commands/workflows/index.md
Added a missing description of the history command
Addend the missing documentation pages
- Fixes #XXXX
=> docs(workflows command): add the description of the history command 

docs/getting-started/configure-resoto/aws.md, docs/getting-started/configure-resoto/gcp.md, docs/getting-started/configure-resoto/kubernetes.md, docs/reference/configuration/worker.md, versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/aws.md, versioned_docs/version-3.X/getting-started/configure-resoto/aws.md, versioned_docs/version-3.X/getting-started/configure-resoto/gcp.md, versioned_docs/version-3.X/getting-started/configure-resoto/kubernetes.md, versioned_docs/version-3.X/reference/configuration/worker.md
=> feat(docs): update Getting Started instructions to write home directory files via the worker config

docs/getting-started/index.md, src/pages/index.tsx
Adds structured data to Getting Started page and fixes search box schema on homepage.
=> fix: add/correct structured data

tools/export_model_images.py
=> fix: model generation

docs/reference/cli/index.md, docs/reference/cli/miscellaneous-commands/apps/edit.md, docs/reference/cli/miscellaneous-commands/apps/index.md, docs/reference/cli/miscellaneous-commands/apps/info.md, docs/reference/cli/miscellaneous-commands/apps/install.md, docs/reference/cli/miscellaneous-commands/apps/list.md, docs/reference/cli/miscellaneous-commands/apps/run.md, docs/reference/cli/miscellaneous-commands/apps/search.md, docs/reference/cli/miscellaneous-commands/apps/uninstall.md, docs/reference/cli/miscellaneous-commands/apps/update.md, docs/reference/cli/miscellaneous-commands/index.md, versioned_docs/version-3.X/reference/cli/index.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/edit.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/index.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/info.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/install.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/list.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/run.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/search.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/uninstall.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/apps/update.md, versioned_docs/version-3.X/reference/cli/miscellaneous-commands/index.md
=> feat(docs): add infrastructure apps CLI docs

blog/resoto-infrastructure-apps/index.mdx, blog/resoto-search-101/index.mdx
Blog Post Infra Apps
Still needs a link at the end to the future Infra Apps documentation.
=> feat(blog): Resoto Infra Apps post

src/components/HomepageModules/img/caret-left.svg, src/components/HomepageModules/img/caret-right.svg, src/components/HomepageModules/index.tsx, src/components/HomepageModules/styles.module.css, src/css/styles.css, src/pages/chronolog/index.tsx, src/pages/sentinel/index.tsx, src/pages/styles.module.css
Adds buttons to scroll the homepage module tabs.
=> feat: home page module tab scroll buttons

docs/how-to-guides/alerting/send-discord-notifications/index.mdx, docs/how-to-guides/alerting/send-slack-notifications/index.mdx, versioned_docs/version-3.X/how-to-guides/alerting/send-discord-notifications/index.mdx, versioned_docs/version-3.X/how-to-guides/alerting/send-slack-notifications/index.mdx
Corresponding Resoto PR: https://github.com/someengineering/resoto/pull/1686
=> docs: update slack and discord howtos

blog/product-updates/2024/february/index.mdx
=> docs: products Update February 2024

docusaurus.config.ts
=> fix: update Discord vanity url
