someengineering/resoto.com

- docs/getting-started/installing-with-kubernetes.md
The call to `resh` was empty.
Also it would make sense to use static login/dbname resoto instead of assigning shell variables because further down in the yaml file we do not make it clear to the user that they have to substitute those values manually with the ones previously generated.
This way they can just copy'paste the file and it'll work.
> Add missing `resh` call and use static login/db name

- news/2022-02-02-v2.0.0.14.md
- tools/release_notes.py
The script can be used to generate release notes.
It still is not able to mark highlights of a release, but it simplifies the tedious part.
Usage (cwd in the repository, since it uses `git log`):
```
python release_notes.py <from_tag> <to_tag>
```
The file here has been generated with:
```
python release_notes.py 2.0.0a13 2.0.0a14
```
- Fixes #XXXX
> feat: Add release notes for 2.0.0a14 and a script to create release notes

- docs/concepts/security.md
- docs/getting-started/installing-with-docker.md
- docs/getting-started/installing-with-kubernetes.md
- docs/getting-started/performing-searches.md
- docs/index.md
- patches/copybutton.patch
- patches/copybutton.sh
- src/theme/CodeBlock/CopyButton/index.js
- src/theme/CodeBlock/CopyButton/styles.module.css
Swizzle CodeBlock/CopyButton to remove leading > and $ signs when copying to clipboard and completely remove lines starting with [`\u200b` (ZERO WIDTH SPACE)](https://unicode-table.com/en/200B/).
The updated code blocks in various files are mainly for testing the JS code. There's more docs to be updated once this is merged.
Added `patches/copybutton.patch/.sh` files to make it easy to reapply the swizzle on upgrades.
> feat(codeblock/copybutton): swizzle CodeBlock/CopyButton to remove leading shell signs in codeblock

- docs/reference/api.md
- src/css/custom.css
Redocusaurus has a component designed to be embedded in docs pages as of v1.1.0. This component gives the API reference less of a "squished" appearance due to the its slightly modified layout.
> fix(docs): use new ApiDocMdx component for API reference

- docs/getting-started/configuration/cloud-providers/aws.md
Aligns the text description of the configuration with the snippet. I guess this was a copy & paste mistake.
> fix(docs): aligns description and config snippet

- openapi/resotocore-edge.yml
Updates `edge` Resoto Core API documentation to reflect changes in [`805515b8e17f9216140a41d55c6c3518c3c0998a`](https://github.com/someengineering/resoto/commit/805515b8e17f9216140a41d55c6c3518c3c0998a).
> feat(docs): update edge API documentation

- docs/getting-started/configure-cloud-provider-access/aws.md
- docs/getting-started/configure-cloud-provider-access/digitalocean.md
- docs/getting-started/configure-cloud-provider-access/gcp.md
- docs/getting-started/configure-cloud-provider-access/kubernetes.md
- docs/getting-started/install-resoto/docker.md
- news/2022/04-22-2.0.2/index.md
- news/2022/04-28-2.1.0/index.md
- news/2022/08-16-2.4.0/index.md
- news/2022/10-05-2.4.2/index.md
- news/2022/10-11-2.4.3/index.md
- news/2022/10-19-2.4.4/index.md
- package.json
- versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/aws.md
- versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/digitalocean.md
- versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/gcp.md
- versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/kubernetes.md
- versioned_docs/version-2.X/getting-started/install-resoto/docker.md
- yarn.lock
Adds notes to each place where `docker-compose` command is used.
> fix(docs): restore note about Compose V1 vs V2 command

- docs/getting-started/install-resoto/docker.md
- versioned_docs/version-2.X/getting-started/install-resoto/docker.md
Since the downloads dir fix is currently only in `main` and not a release branch, the note was only added to the `edge` docs.
If the change is cherrypicked to a release branch, the `2.4` versioned doc should also be updated.
> fix(docs): number Docker install steps and add note about download dir

- docusaurus.config.js
- package.json
- src/theme/DocVersionBanner/index.tsx
- yarn.lock
Stops Docusaurus from persisting the docs version in local storage and using that value for conceptual search.
Also bumps dependencies.
> fix(search): always show results from stable docs except within edge docs

- docusaurus.config.js
- yarn.lock
Add code highlighting for Ruby, C#, and PHP.
> fix: code highlighting for Ruby, C#, and PHP

- src/css/docusaurus-plugin-openapi-docs.css
Define value `--openapi-input-background` to fix dropdown background color in dark mode.
> fix(docs): dropdown background color

- src/css/docusaurus-plugin-openapi-docs.css
- src/theme/DocCard/index.tsx
- src/theme/DocCard/styles.module.css
Shows API method type in `DocCard` list, similar to how they are shown in the sidebar.
> feat: show API method type in DocCards

- docs/reference/api/proxy-request-to-a-configured-tsdb-server.api.mdx
- docs/reference/api/sidebar.js
- docs/reference/api/tsdb.tag.mdx
- openapi/resotocore-edge.yml
Updates `edge` Resoto Core API documentation to reflect changes in [`16137a915437a1fbd6cc44ac0b1af9a9d37cb499`](https://github.com/someengineering/resoto/commit/16137a915437a1fbd6cc44ac0b1af9a9d37cb499).
> feat(docs): update edge documentation

- src/pages/index.module.css
- yarn.lock
Explicitly define `width` of hero animation. Needed due to Safari flexbox bug.
> fix(homepage): resolve hero display issue in older versions of Safari

- docs/concepts/index.md
- docs/contributing/index.md
- docs/getting-started/configure-cloud-provider-access/index.md
- docs/getting-started/index.md
- docs/getting-started/install-resoto/aws/cdk.md
- docs/getting-started/install-resoto/aws/cloudformation.md
- docs/getting-started/install-resoto/docker.md
- docs/getting-started/install-resoto/index.md
- docs/getting-started/install-resoto/kubernetes.md
- docs/getting-started/install-resoto/pip.md
- docs/how-to-guides/index.md
- docs/index.md
- docs/reference/index.md
- package.json
- src/components/SectionedDocCardList.tsx
- src/theme/CodeBlock/index.tsx
- versioned_docs/version-2.X/concepts/index.md
- versioned_docs/version-2.X/contributing/index.md
- versioned_docs/version-2.X/getting-started/configure-cloud-provider-access/index.md
- versioned_docs/version-2.X/getting-started/index.md
- versioned_docs/version-2.X/getting-started/install-resoto/aws/cdk.md
- versioned_docs/version-2.X/getting-started/install-resoto/aws/cloudformation.md
- versioned_docs/version-2.X/getting-started/install-resoto/docker.md
- versioned_docs/version-2.X/getting-started/install-resoto/index.md
- versioned_docs/version-2.X/getting-started/install-resoto/kubernetes.md
- versioned_docs/version-2.X/getting-started/install-resoto/pip.md
- versioned_docs/version-2.X/how-to-guides/index.md
- versioned_docs/version-2.X/index.md
- versioned_docs/version-2.X/reference/index.md
- yarn.lock
- Remove/correct navigation on some docs pages
- Note that pip can only be used to install tagged versions, and specify version in command
- Remove debugging code for `SectionedDocCardList` component
> fix(docs): correct prev/next navigation & note that pip install not available for edge

- blog/authors.yml
- docusaurus.config.js
- package.json
- static/_redirects
- static/robots.txt
- svgo.config.js
- yarn.lock
- Canonical fix for 2.X versioned docs
- Avoid redirect for GH avatars
- Enable multipass for SVGO
- Add redirects for nonexistent tags
- Add `og:type` meta tag
> fix: workaround for 2.X docs canonical casing

- docs/getting-started/install-resoto/docker.md
- src/theme/CodeBlock/index.tsx
- versioned_docs/version-2.X/getting-started/install-resoto/docker.md
- versioned_docs/version-3.X/getting-started/install-resoto/docker.md
- yarn.lock
Updates Docker install instructions to use `docker-compose.yaml` release artifacts rather than a repo file.
Release assets have been added for 2.4.7 and 3.0.3, so this can be merged immediately.
> fix(docs): update Docker install docs

- netlify/functions/submission-created.ts
- src/components/NewsletterSignupForm/index.tsx
For debugging purposes; email signup seems broken at the moment.
> fix: capture referrer URL in email signup form & add console logging to serverless function

- versioned_sidebars/version-3.X-sidebars.json
Versioned sidebars need to be manually updated when API routes are added/removed.
> fix(docs): missing API sidebar entries

- compare/aws-config.mdx
updated the number of resource types that both Config and Resoto support. I changed it from "resources" to "resource types".
> fix(compare): edit AWS Config comparison chart
